name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Install dependencies
        run: swift package resolve
      - name: Build
        run: swift build --build-tests
